* more work on dynamic segmenter plugins   - move builtin segmenter to another file   - don't hardcode default segmenter methods   - keep track of initial load directory for when current dir changes   - add summary line displaying the segment method when analyzing a text   - new methods to load plugins   - PrefsDialog use segHelper instead of self.config   - plugin classes create an init and setup method; no longer need cls and key, just name and description
* redid prefs layout

* method parameter name changes:
  - format -> formatType
  - method -> segmentMethod

* wxPython changes
(for 3.0)
PySimpleApp -> wx.App
(for 4.0)
ListBox.SetSelection(idx, True) -> ListBox.SetSelection(idx)
  - fixes ListBox.SetSelection(): too many arguments
SelectableTextCtrl(the tabbed panels).SetMaxLength(1e9) ->.SetMaxLength(int(1e9))
  - fixes TextEntry.SetMaxLength(): argument 1 has unexpected type 'float'
FileDialog style=wx.OPEN... -> style=wx.FD_OPEN...
  - fixes AttributeError: 'module' object has no attribute 'OPEN'

* New files
BUILDING
segmenter/plugins/segmentmethod_simple_longest.py